version: '3.7'
services:
  order-database:
    container_name: order-database
    image: postgres:13-alpine
    ports: 
    - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - order_database:/var/lib/postgresql/data:delegated
    networks:
    - order-network
  order-api:
    container_name: order-api
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
    - ${API_PORT}:8080
    depends_on:
    - order-database
    networks:
    - order-network
volumes:
  order_database: null
networks:
  order-network:
    driver: bridge